### PR TITLE
Update dependencies to work with Ruby 3.0.0

### PR DESCRIPTION
**Pull request by nerab**
Bumping httparty was necessary because the old version failed with `undefined method `encode' for URI:Module (NoMethodError)`.

I also relaxed a few dependencies and removed `auth_params` from the tests as they do not make a difference.

### CODE REVIEW

**Comment by nerab** [comment]
Oops, something went wrong with the tests in Travis. Checking...

**Comment by nerab** [comment]
Build is good again. Please consider merging and perhaps a new gem release? 🙏
